In [4]:
%pylab inline  
import GPy
import GPyOpt
from numpy.random import seed

Populating the interactive namespace from numpy and matplotlib


In [5]:
def myf(x):
    return (2*x)**2

In [6]:
bounds = [{'name': 'var_1', 'type': 'continuous', 'domain': (-1,1)}]

In [7]:
max_iter = 15

In [8]:
myProblem = GPyOpt.methods.BayesianOptimization(myf,bounds)

In [33]:
myProblem.run_optimization(max_iter)

In [34]:
myProblem.cum_time

0

In [44]:
y =[1,2]

In [45]:
yy = np.atleast_2d(y)

In [48]:
yy

array([[1, 2]])

In [57]:
np.delete(yy,1)

array([1])

In [52]:
a = 1
a += 1

In [55]:
abs(2-1)

1

In [41]:
numpy.random.choice(numpy.arange(1, 7), p=[0.1, 0.05, 0.05, 0.2, 0.4, 0.2])

4

In [12]:
myProblem.model.predict(myProblem.X)

(array([[-0.7296662 ],
        [-0.77305225],
        [ 1.80810298],
        [-0.67905293],
        [ 0.37366839]]), array([[ 0.00010058],
        [ 0.00010058],
        [ 0.00010058],
        [ 0.00010058],
        [ 0.00010058]]))

In [9]:
from GPyOpt.util.general import get_quantiles
from GPyOpt.acquisitions.GES import AcquisitionGES

In [11]:
m, V = myProblem.model.predict(myProblem.X, full_cov=True)
ges = AcquisitionGES(myProblem.model, myProblem.space)
pmin = ges.joint_pmax(m, V, 500)
pmin

array([  1.00000000e-70,   1.00000000e-70,   1.00000000e+00,
         1.00000000e-70,   1.00000000e-70])

In [108]:
m.shape

(33, 1)

In [109]:
pmin.shape

(33,)

In [118]:
sum(np.multiply(m.flatten(),pmin))


-0.59965233571631871

In [119]:
m.flatten-E

TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'float'

In [122]:
V = sum((m.flatten()-E)**2*pmin)

In [123]:
V

4.4572504418284537e-15

In [48]:
print(myProblem.model.model)


Name : GP regression
Objective : -105.32813800471752
Number of Parameters : 3
Number of Optimization Parameters : 3
Updates : True
Parameters:
  GP_regression.           |               value  |  constraints  |  priors
  Mat32.variance           |       1684.55618958  |      +ve      |        
  Mat32.lengthscale        |       23.4794861149  |      +ve      |        
  Gaussian_noise.variance  |  5.56268464627e-309  |      +ve      |        


In [17]:
myProblem.model.get_model_parameters()

array([[  4.93176740e+002,   1.15991427e+001,   3.37787084e-190]])

In [26]:
input("Press Enter to continue...")

Press Enter to continue...print(myProblem)


'print(myProblem)'